"""MAZE TOPOLOGY AUDIT (per Codex review):

Wall-follower trivially solves tree-like mazes (the kind generated by
recursive backtracking). Codex critique: "wall-following at 100% screams
perfect/simply-connected maze artifact."

This launcher generates LOOPY mazes (multi-path topology) by adding
random extra openings to the recursive-backtracking output. With loops,
the left-hand rule can get caught in inner loops and fail.

We test all main agents on:
  - 'tree': original mazes (matches main sweep)
  - 'loopy_30': add 30% extra openings
  - 'loopy_60': add 60% extra openings

3 topologies x 5 agents x 20 seeds x 3 sizes = 900 runs

If wall-following STAYS at 100% on loopy mazes too, the prior is robust.
If wall-following DROPS, we report this honestly.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from experiment_lib_v2 import (
    NoBacktrackRandomAgent, RandomAgent, FeatureQAgent, MLPDQNAgent,
    make_maze, ego_features, is_solvable, ACTIONS, WALL,
    OBS_DIM, NUM_ACTIONS,
    load_checkpoint, save_checkpoint, run_key, atomic_save,
    set_all_seeds, code_hash,
    run_experiment,
)
from maze_env_helpers import step_env
from launch_wall_following import WallFollower, DFSAgent
from launch_wall_follow_egofeats import EgoOnlyWallFollower

import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

SEEDS = [42, 123, 456, 789, 1024, 2048, 3072, 4096, 5120, 6144,
         7168, 8192, 9216, 10240, 11264, 12288, 13312, 14336, 15360, 16384]
SIZES = [9, 13, 17]
NUM_TRAIN = 100
NUM_TEST = 50

OUT_DIR = Path(__file__).parent / "raw_results" / "exp_loopy_mazes"
CHECKPOINT_FILE = OUT_DIR / "checkpoint.json"


def make_loopy_maze(size: int, seed: int, extra_openings_frac: float = 0.0) -> list:
    """Start with tree maze, add extra interior openings to create loops."""
    maze = make_maze(size, seed=seed)
    if extra_openings_frac <= 0:
        return maze
    rng = np.random.default_rng(seed * 7 + 991)
    # Find all interior wall positions (not boundary)
    candidates = []
    for r in range(2, size - 2):
        for c in range(2, size - 2):
            if maze[r][c] == WALL:
                # Open this wall ONLY if it has open neighbors on opposite sides
                # (so it really creates a shortcut, not a dead-end opening)
                horiz = (maze[r][c - 1] != WALL and maze[r][c + 1] != WALL)
                vert = (maze[r - 1][c] != WALL and maze[r + 1][c] != WALL)
                if horiz or vert:
                    candidates.append((r, c))
    n_open = int(extra_openings_frac * len(candidates))
    chosen_idx = rng.choice(len(candidates), size=min(n_open, len(candidates)), replace=False)
    new_maze = [row.copy() if hasattr(row, "copy") else list(row) for row in maze]
    for i in chosen_idx:
        r, c = candidates[i]
        new_maze[r][c] = 0
    return new_maze


def trace_agent(maze, agent, agent_kind: str, gx: int, gy: int, n: int) -> tuple:
    if hasattr(agent, "reset"):
        agent.reset()
    if hasattr(agent, "reset_for_new_maze"):
        agent.reset_for_new_maze()
    ax, ay = 1, 1
    action_hist: list = []
    max_steps = 4 * n * n
    step = 0
    for step in range(max_steps):
        if agent_kind == "wallfollow_full":
            action = agent.act(maze, (ay, ax))  # legacy WallFollower wants (row, col)
        elif agent_kind == "wallfollow_ego":
            obs = np.array(ego_features(maze, ax, ay, gx, gy, n, action_hist), dtype=np.float32)
            action = agent.act(obs)
        elif agent_kind == "dfs":
            action = agent.act(maze, (ay, ax))
        else:
            obs = np.array(ego_features(maze, ax, ay, gx, gy, n, action_hist), dtype=np.float32)
            if hasattr(agent, "eval_action"):
                action = agent.eval_action(obs)
            else:
                action = agent.act(obs, step)
        new_ax, new_ay, _, _, _ = step_env(maze, ax, ay, action, n)
        ax, ay = new_ax, new_ay
        action_hist.append(action)
        if (ax, ay) == (gx, gy):
            return True, step + 1
    return False, max_steps


def is_solvable_arbitrary(maze, n) -> bool:
    """BFS solvability check that doesn't depend on lib's avoid_hazards."""
    from collections import deque
    visited = {(1, 1)}
    queue = deque([(1, 1)])
    while queue:
        r, c = queue.popleft()
        if (r, c) == (n - 2, n - 2):
            return True
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if 0 <= nr < n and 0 <= nc < n and (nr, nc) not in visited and maze[nr][nc] != WALL:
                visited.add((nr, nc))
                queue.append((nr, nc))
    return False


def run_one(agent_factory, agent_kind: str, topology: str, frac: float,
            size: int, seed: int, n_test: int) -> dict:
    rng = np.random.default_rng(seed + 1_000_000)
    solved = 0
    total_steps = 0
    test_seeds: list[int] = []
    while len(test_seeds) < n_test:
        s = int(rng.integers(0, 10**9))
        m = make_loopy_maze(size, seed=s, extra_openings_frac=frac)
        if is_solvable_arbitrary(m, size):
            test_seeds.append(s)
    for s in test_seeds:
        maze = make_loopy_maze(size, seed=s, extra_openings_frac=frac)
        agent = agent_factory()
        gx, gy = size - 2, size - 2
        success, steps = trace_agent(maze, agent, agent_kind, gx, gy, size)
        if success:
            solved += 1
        total_steps += steps
    return {"n_eps": n_test, "solved": solved,
            "success_rate": solved / n_test,
            "mean_steps": total_steps / n_test}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    completed = load_checkpoint(CHECKPOINT_FILE)

    TOPOLOGIES = [("tree", 0.0), ("loopy_30", 0.30), ("loopy_60", 0.60)]
    AGENTS = [
        ("Random",            lambda: RandomAgent(),                           "neural"),
        ("NoBackRandom",      lambda: NoBacktrackRandomAgent(),                "neural"),
        ("WallFollowerLeft",  lambda: WallFollower(side="left"),               "wallfollow_full"),
        ("EgoWallFollower",   lambda: EgoOnlyWallFollower(side="left"),        "wallfollow_ego"),
        ("DFSAgent",          lambda: DFSAgent(),                              "dfs"),
    ]
    total = len(TOPOLOGIES) * len(AGENTS) * len(SIZES) * len(SEEDS)
    done = len(completed)
    print(f"\nLoopy maze topology audit: {total} runs, {done} done")
    print(f"Topologies: {[t[0] for t in TOPOLOGIES]}")
    print(f"Code hash: {code_hash()}\n")

    for topology, frac in TOPOLOGIES:
        for agent_name, factory, kind in AGENTS:
            for size in SIZES:
                for seed in SEEDS:
                    composite = f"{topology}__{agent_name}"
                    key = run_key(composite, size, seed)
                    if key in completed:
                        continue
                    print(f"  [{done}/{total}] {composite} {size}x{size} s={seed}...",
                          end=" ", flush=True)
                    t0 = time.time()
                    result = run_one(factory, kind, topology, frac, size, seed, NUM_TEST)
                    elapsed = time.time() - t0
                    run_file = OUT_DIR / f"{composite}_{size}_{seed}.json"
                    atomic_save([{
                        "agent_name": composite,
                        "base_agent": agent_name,
                        "topology": topology,
                        "extra_openings_frac": frac,
                        "maze_size": size,
                        "seed": seed,
                        "phase": "test",
                        "wall_time_s": elapsed,
                        "code_hash": code_hash(),
                        **result,
                    }], run_file)
                    completed.add(key)
                    save_checkpoint(CHECKPOINT_FILE, completed)
                    done += 1
                    print(f"done ({elapsed:.1f}s) test={100*result['success_rate']:.0f}%")

    print(f"\nLoopy maze audit complete in {OUT_DIR}")


if __name__ == "__main__":
    main()
