use crate::types::{ModuleId, ModuleSnapshot, SpikeEvent, SimTime};

/// The core abstraction for brain region modules.
///
/// Every brain module (sensory encoder, associative memory, etc.) implements
/// this trait. The runtime orchestrator calls these methods in sequence during
/// each tick of the cognitive loop.
pub trait BrainModule: Send {
    /// Unique identifier for this module
    fn id(&self) -> ModuleId;

    /// Process incoming spikes and produce outgoing spikes.
    ///
    /// This is the main computation step. The module receives spikes from
    /// other modules (routed by the runtime), updates its internal neuron
    /// states, and returns any spikes generated by its neurons.
    fn step(
        &mut self,
        dt: f64,
        sim_time: SimTime,
        incoming_spikes: &[SpikeEvent],
    ) -> Vec<SpikeEvent>;

    /// Generate a lightweight snapshot for dashboard visualization.
    /// Called at 30fps -- must be cheap.
    fn snapshot(&self) -> ModuleSnapshot;

    /// Reset the module to its initial state (for episode boundaries)
    fn reset(&mut self);

    /// Number of neurons in this module
    fn neuron_count(&self) -> u32;

    /// Serialize state for checkpointing
    fn save_state(&self) -> Vec<u8>;

    /// Restore state from checkpoint
    fn load_state(&mut self, data: &[u8]);
}
